[workspace]
members = ["takzero", "train", "puzzle", "evaluation", "graph"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

[profile.release-with-debug]
inherits = "release"
debug = true
