[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
float-ord = "0.3.2"

fast-tak = "0.3.2"

rand_distr = "0.4.3"
rand = "0.8.5"
# mimalloc = { version = "0.1.37", default-features = false }
