[package]
name = "search"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
fast-tak = "0.3.0"
rand_distr = "0.4.3"
rand = "0.8.5"
float-ord = "0.3.2"
mimalloc = { version = "0.1.37", default-features = false }
