[package]
name = "takzero"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-tak = "0.3.4"
float-ord = "0.3.2"
ordered-float = "3.7.0"
rayon = "1.7.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_chacha = "0.3.1"
tch = "0.13.0"
