[package]
name = "rnd_experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
fast-tak.workspace = true
rand.workspace = true
rayon.workspace = true
takzero.workspace = true
tch.workspace = true
charming = "0.2.4"
