[package]
name = "visualize_search"
version = "0.1.0"
edition = "2021"

[dependencies]
tch.workspace = true
takzero.workspace = true
fast-tak.workspace = true
rand.workspace = true
svg = "0.17.0"

[lints]
workspace = true
