[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
takzero = { path = "../takzero" }
rayon = "1.7.0"
tch = "0.13.0"
log = "0.4.20"
env_logger = "0.10.0"
clap = { version = "4.4.0", features = ["derive"] }
