[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
env_logger.workspace = true
fast-tak.workspace = true
log.workspace = true
rayon.workspace = true
takzero.workspace = true
tch.workspace = true
